In [2]:
import torch

# 创建一个一维张量
tensor1 = torch.tensor([1, 2, 3, 4])
print(tensor1)

# 创建一个二维张量
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor2)

tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])


In [10]:
# 创建一个形状为 (2, 3) 的全零张量
zeros_tensor = torch.zeros(2, 3)
zeros_tensor = zeros_tensor.to(dtype=torch.int32)
print(zeros_tensor)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [12]:
# 创建一个形状为 (2, 3) 的全一张量
ones_tensor = torch.ones(2, 3)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# 创建一个形状为 (2, 3) 的未初始化张量
empty_tensor = torch.empty(2, 3)
print(empty_tensor)

tensor([[7.8963e-31, 1.4952e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [17]:
# 创建一个从 0 到 10 的均匀分布的张量，包含 5 个元素
linspace_tensor = torch.linspace(0, 10, steps=5)
print(linspace_tensor)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [20]:
# 创建一个形状为 (2, 3) 的随机张量
rand_tensor = torch.rand(3, 3)
print(rand_tensor)

tensor([[0.6951, 0.5778, 0.2056],
        [0.5707, 0.6547, 0.3161],
        [0.2001, 0.8744, 0.4938]])


In [22]:
# 创建一个形状为 (2, 3) 的正态分布随机张量
randn_tensor = torch.randn(2, 3)
print(randn_tensor)

tensor([[ 1.1497,  1.0452,  0.3856],
        [ 1.7059, -0.9896,  1.2560]])


In [25]:
# 创建一个形状为 (2, 3) 的正态分布随机张量
randn_tensor = torch.rand(2, 3)
print(randn_tensor)

tensor([[0.9807, 0.2285, 0.8956],
        [0.6073, 0.0650, 0.3971]])


In [28]:
# 创建一个形状为 (2, 3) 的张量，填充值为 5
full_tensor = torch.full((2, 3), 1)
print(full_tensor)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [82]:
diag_elements = torch.tensor([1, 2, 3])

# 使用 torch.diag() 创建对角矩阵
diag_matrix = torch.diag(diag_elements)
print(diag_matrix)
torch.transpose(diag_matrix, 1,0)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [86]:
x = torch.tensor([[3, 2], [3, 4]])
y = torch.transpose(x, 0, 1)
x,y

(tensor([[3, 2],
         [3, 4]]),
 tensor([[3, 3],
         [2, 4]]))

In [119]:
x = torch.randn(32, 3, 4)
y = x.permute(1, 2, 0)
print(y.shape)  # 输出：torch.Size([4, 2, 3])

torch.Size([3, 4, 32])


In [126]:
x = torch.randn(32, 10, 1)
y = torch.squeeze(x)
x.shape,y.shape

(torch.Size([32, 10, 1]), torch.Size([32, 10]))

In [134]:
x = torch.tensor([1, 2, 3])
y = torch.unsqueeze(x, 0)
x.shape,y.shape

(torch.Size([3]), torch.Size([1, 3]))

In [138]:
x = torch.randn(32, 10, 1)
y = torch.flatten(x)
x.shape,y.shape

(torch.Size([32, 10, 1]), torch.Size([320]))

In [164]:
x = torch.randn(3, 3, 1)
y = torch.chunk(x, 3)
y# 输出：(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))

(tensor([[[ 0.1402],
          [ 1.8509],
          [-1.2267]]]),
 tensor([[[-0.6810],
          [-0.0759],
          [-0.8846]]]),
 tensor([[[0.8851],
          [0.0465],
          [0.1826]]]))

In [161]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=0)
print(z)  # 输出：tensor([[1, 2], [3, 4], [5, 6], [7, 8]])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [174]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=0)
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [206]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.concat((x, y), dim=1)
print(z)
# 输出：
# tensor([[1, 2],
#         [3, 4],
#         [5, 6],
#         [7, 8]])

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [208]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = torch.split(x, 2)
print(y)
# 输出：
# (tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))

(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [233]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = torch.hsplit(x, 3)
print(y)
# 输出：
# (tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [241]:
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y = torch.dsplit(x, 2)
x,y

# 输出：
# (tensor([[[1], [3]], [[5], [7]]]), tensor([[[2], [4]], [[6], [8]]]))

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 (tensor([[[1],
           [3]],
  
          [[5],
           [7]]]),
  tensor([[[2],
           [4]],
  
          [[6],
           [8]]])))

In [261]:
x = torch.tensor([3, 3, 3],dtype=torch.float32)
x.mean()

tensor(3.)

In [267]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float32)
var_all = torch.var(x)  # 计算所有元素的方差
var_dim0 = torch.var(x, dim=0)  # 沿第0维计算方差
var_dim1 = torch.var(x, dim=1)  # 沿第1维计算方差
print(var_all)  # 输出：tensor(2.9167)
print(var_dim0)  # 输出：tensor([2.2500, 2.2500, 2.2500])
print(var_dim1)  # 输出：tensor([0.6667, 0.6667])

tensor(3.5000)
tensor([4.5000, 4.5000, 4.5000])
tensor([1., 1.])


In [269]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float32)
std_dim0 = torch.std(x, dim=0)  # 沿第0维计算标准差
std_dim1 = torch.std(x, dim=1)  # 沿第1维计算标准差
print(std_all)  # 输出：tensor(1.7078)
print(std_dim0)  # 输出：tensor([1.5000, 1.5000, 1.5000]
print(std_dim1)  # 输出：tensor([0.8165, 0.8165])

tensor(1.8708)
tensor([2.1213, 2.1213, 2.1213])
tensor([1., 1.])
