In [5]:
.import torch

In [6]:
23lpo0_P"{\|54\【。x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
x_int = x.to(torch.int32)  # 转换为32位整数
x_bool = x.to(torch.bool)  # 转换为布尔类型

In [7]:
x_bool.shape,x_bool.size(0)

(torch.Size([3]), 3)

In [8]:
tensor1 = torch.tensor([1, 2, 3, 4])
tensor2 = torch.tensor([[1, 2], [3, 4]])
tensor1,tensor2

(tensor([1, 2, 3, 4]),
 tensor([[1, 2],
         [3, 4]]))

In [9]:
zeros_tensor = torch.zeros(1,1,2,2,dtype=torch.int32)
zeros_tensor

tensor([[[[0, 0],
          [0, 0]]]], dtype=torch.int32)

In [10]:
ones_tensor = torch.ones(2, 3,dtype=torch.int32)
ones_tensor

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [11]:
empty_tensor = torch.empty(2, 3)
empty_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
arange_tensor = torch.arange(1,4)
arange_tensor
"""tensor([1, 2, 3])"""

'tensor([1, 2, 3])'

In [13]:
linspace_tensor = torch.linspace(0, 10, steps=10)
linspace_tensor
"""
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
"""

'\ntensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,\n         8.8889, 10.0000])\n'

In [14]:
randn_tensor = torch.randn(2, 3)
randn_tensor

tensor([[ 0.4123, -1.0047,  0.7651],
        [ 1.1695, -0.2113, -1.1708]])

In [15]:
# 创建一个形状为 (2, 3) 的张量，填充值为 5
full_tensor = torch.full((2, 3,4,4), 550)
full_tensor

tensor([[[[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]],

         [[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]],

         [[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]]],


        [[[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]],

         [[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]],

         [[550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550],
          [550, 550, 550, 550]]]])

In [18]:
eye_tensor = torch.eye(3)
print(eye_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [17]:

iag_elements = torch.tensor([1, 2, 3])

# 使用 torch.diag() 创建对角矩阵;'

diag_matrix = torch.diag(diag_elements)
print(diag_matrix)

NameError: name 'diag_elements' is not defined